const express = require('express');

/* GET home page. */
exports.upload_get = function (req, res, next) {
    res.render('index', { title: 'Vocabularize' });
};

// Handle POST.
exports.upload_post = function (req, res) {

    var upload = req.file;    
    var text = upload.buffer;
    
    var output = text + "--- this vocab was generated by vocabularize ---";

    res.render('index', {  title: 'Vocabularize' , output: output });
};